// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzrhdeccmfdymayvfmqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6cmhkZWNjbWZkeW1heXZmbXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MDcxMzYsImV4cCI6MjA1MDI4MzEzNn0.vyebgsZ6BMlSFhWBC7-UMmqMEQLAyZEis9FKupDBQ_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);